// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

<<<<<<< HEAD
=======
import AreaAutocompleteController from "./area_autocomplete_controller"
application.register("area-autocomplete", AreaAutocompleteController)

>>>>>>> 4a8a396a41dd4df351d6326a6e67db1721ea753b
import FilterTypeController from "./filter_type_controller"
application.register("filter-type", FilterTypeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
